// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AIDlink contributors
//
// GENERATED by tools/gen_globe_font.py: a single-glyph LVGL font carrying a
// globe icon at U+1F310 for the display's internet-connectivity indicator —
// the built-in Montserrat symbol set has no globe. Span/label text is
// "\xF0\x9F\x8C\x90".
#include "sdkconfig.h"
#if CONFIG_IDF_TARGET_ESP32S3   // LVGL exists only on the display-capable target
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    0x00, 0x00, 0x26, 0x86, 0x20, 0x00, 0x00,
    0x00, 0x1a, 0xfc, 0x9c, 0xfa, 0x10, 0x00,
    0x01, 0xdb, 0xe2, 0x02, 0xeb, 0xd1, 0x00,
    0x0a, 0xa5, 0x90, 0x00, 0x95, 0xaa, 0x00,
    0x2f, 0x17, 0x50, 0x00, 0x57, 0x1f, 0x20,
    0x6b, 0x09, 0x40, 0x00, 0x49, 0x0b, 0x60,
    0x8f, 0xff, 0xff, 0xff, 0xff, 0xff, 0x80,
    0x6b, 0x09, 0x40, 0x00, 0x49, 0x0b, 0x60,
    0x2f, 0x17, 0x50, 0x00, 0x57, 0x1f, 0x20,
    0x0a, 0xa5, 0x90, 0x00, 0x95, 0xaa, 0x00,
    0x01, 0xdb, 0xe2, 0x02, 0xeb, 0xd1, 0x00,
    0x00, 0x1a, 0xfc, 0x9c, 0xfa, 0x10, 0x00,
    0x00, 0x00, 0x26, 0x86, 0x20, 0x00, 0x00,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id 0 reserved */,
    {.bitmap_index = 0, .adv_w = 208, .box_w = 13, .box_h = 13, .ofs_x = 0, .ofs_y = 0},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 0x1F310, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t font_globe = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 13,
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
};
#endif  // CONFIG_IDF_TARGET_ESP32S3
