// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AIDlink contributors
//
// GENERATED by tools/gen_cloud_font.py: single-glyph LVGL font with a cloud
// (internet reachability) icon at U+2601. Padding baked into adv_w/ofs_x;
// span/label text is just "\xE2\x98\x81".
#include "sdkconfig.h"
#if CONFIG_IDF_TARGET_ESP32S3   // LVGL exists only on the display-capable target
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x03, 0x77, 0x30, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x8f, 0xff, 0xf8, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x17, 0xff, 0xff, 0xff, 0x60, 0x00, 0x00,
    0x00, 0x1a, 0xff, 0xff, 0xff, 0xff, 0xd7, 0x10, 0x00,
    0x00, 0xaf, 0xff, 0xff, 0xff, 0xff, 0xff, 0xe3, 0x00,
    0x01, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfb, 0x00,
    0x01, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfd, 0x00,
    0x00, 0xaf, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfa, 0x00,
    0x00, 0x1a, 0xff, 0xff, 0xff, 0xff, 0xff, 0xc2, 0x00,
    0x00, 0x00, 0x16, 0x66, 0x66, 0x66, 0x63, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id 0 reserved */,
    {.bitmap_index = 0, .adv_w = 336, .box_w = 17, .box_h = 12, .ofs_x = 2, .ofs_y = 0},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 0x2601, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t font_cloud = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 16,
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
};
#endif  // CONFIG_IDF_TARGET_ESP32S3
