// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AIDlink contributors
//
// GENERATED by tools/gen_tod_font.py: single-glyph LVGL font with a TOD
// (top-of-descent) icon at U+2198 — level segment breaking into a descent
// slope. Padding baked into adv_w/ofs_x; span text is just "\xE2\x86\x98".
#include "sdkconfig.h"
#if CONFIG_IDF_TARGET_ESP32S3   // LVGL exists only on the display-capable target
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    0x99, 0x99, 0x99, 0x97, 0x00, 0x00, 0x00, 0x00,
    0xff, 0xff, 0xff, 0xff, 0x80, 0x00, 0x00, 0x00,
    0xbb, 0xbb, 0xbb, 0xdf, 0xf7, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x1d, 0xff, 0x50, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x01, 0xef, 0xf4, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x2e, 0xfe, 0x30, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x04, 0xef, 0xe2, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x5f, 0xfd, 0x10,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0xff, 0xc1,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7f, 0xfb,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0xff,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xaf,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id 0 reserved */,
    {.bitmap_index = 0, .adv_w = 352, .box_w = 16, .box_h = 12, .ofs_x = 3, .ofs_y = 0},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 0x2198, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t font_tod = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 16,
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
};
#endif  // CONFIG_IDF_TARGET_ESP32S3
