// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AIDlink contributors
//
// GENERATED by tools/gen_arrow_font.py: a single-glyph LVGL font carrying
// a real U+27A4 (black rightwards arrowhead) for the route line — the built-in
// Montserrat fonts don't include it. Padding is baked into adv_w/ofs_x, so the
// span text is just "\xE2\x9E\xA4" with no surrounding spaces.
#include "sdkconfig.h"
#if CONFIG_IDF_TARGET_ESP32S3   // LVGL exists only on the display-capable target
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    0x85, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x4f, 0xe8, 0x10, 0x00, 0x00, 0x00, 0x00,
    0x0b, 0xff, 0xfa, 0x30, 0x00, 0x00, 0x00,
    0x04, 0xff, 0xff, 0xfc, 0x50, 0x00, 0x00,
    0x00, 0xbf, 0xff, 0xff, 0xfe, 0x81, 0x00,
    0x00, 0x4f, 0xff, 0xff, 0xff, 0xff, 0xa3,
    0x00, 0x4f, 0xff, 0xff, 0xff, 0xff, 0xa3,
    0x00, 0xbf, 0xff, 0xff, 0xfe, 0x81, 0x00,
    0x04, 0xff, 0xff, 0xfc, 0x50, 0x00, 0x00,
    0x0b, 0xff, 0xfa, 0x30, 0x00, 0x00, 0x00,
    0x4f, 0xe8, 0x10, 0x00, 0x00, 0x00, 0x00,
    0x85, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id 0 reserved */,
    {.bitmap_index = 0, .adv_w = 416, .box_w = 14, .box_h = 12, .ofs_x = 6, .ofs_y = 5},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 0x27A4, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t font_arrow = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 18,
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
};
#endif  // CONFIG_IDF_TARGET_ESP32S3
