// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AIDlink contributors
//
// GENERATED by tools/gen_eta_font.py: single-glyph LVGL font with an ETA
// (arrival) icon at U+25CE — a bullseye/target. Padding baked into
// adv_w/ofs_x; span text is just "\xE2\x97\x8E".
#include "sdkconfig.h"
#if CONFIG_IDF_TARGET_ESP32S3   // LVGL exists only on the display-capable target
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    0x00, 0x00, 0x47, 0x74, 0x00, 0x00, 0x00,
    0x00, 0x4d, 0xff, 0xff, 0xd4, 0x00, 0x00,
    0x04, 0xff, 0xa5, 0x5a, 0xff, 0x40, 0x00,
    0x0d, 0xf5, 0x00, 0x00, 0x5f, 0xd0, 0x00,
    0x4f, 0xa0, 0x2a, 0xa2, 0x0a, 0xf4, 0x00,
    0x7f, 0x50, 0xaf, 0xfa, 0x05, 0xf7, 0x00,
    0x7f, 0x50, 0xaf, 0xfa, 0x05, 0xf7, 0x00,
    0x4f, 0xa0, 0x2a, 0xa2, 0x0a, 0xf4, 0x00,
    0x0d, 0xf5, 0x00, 0x00, 0x5f, 0xd0, 0x00,
    0x04, 0xff, 0xa5, 0x5a, 0xff, 0x40, 0x00,
    0x00, 0x4d, 0xff, 0xff, 0xd4, 0x00, 0x00,
    0x00, 0x00, 0x47, 0x74, 0x00, 0x00, 0x00,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id 0 reserved */,
    {.bitmap_index = 0, .adv_w = 304, .box_w = 13, .box_h = 12, .ofs_x = 3, .ofs_y = 0},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 0x25CE, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t font_eta = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 16,
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
};
#endif  // CONFIG_IDF_TARGET_ESP32S3
