#!/usr/bin/env python3
"""Bump the firmware build number and emit buildnum.h.

Runs on every firmware build (main/CMakeLists.txt custom target): increments
the counter file (shared by both targets, committed to the repo) and writes the
generated header. The number shows on the T-Display splash row and in the web
portal hero/status strip.

Usage: bump_buildnum.py <counter.txt> <out_header.h>
"""
import sys

cnt_path, out_path = sys.argv[1], sys.argv[2]
try:
    n = int(open(cnt_path).read().strip())
except (OSError, ValueError):
    n = 0
n += 1
open(cnt_path, "w").write(f"{n}\n")
open(out_path, "w").write(
    "// GENERATED by tools/bump_buildnum.py — do not edit, do not commit.\n"
    "#pragma once\n"
    f"#define FW_BUILDNUM {n}\n"
)
print(f"firmware build #{n}")
