#!/usr/bin/env python3
"""Generate main/font_arrow.c — a single-glyph LVGL font with a real U+27A4
(black rightwards arrowhead), drawn programmatically (no font tools needed).
4bpp, 8x supersampled antialiasing, padding baked into adv_w/ofs_x."""

W, H = 14, 12          # glyph box
PAD = 6                # visual padding each side, via ofs_x / adv_w
SS = 8                 # supersampling factor
NOTCH = 3.0            # concave back depth (the arrowhead 'tail bite')

def inside(px, py):
    # coordinates in glyph space: x 0..W, y 0..H (y down)
    t = abs(2.0 * py / H - 1.0)            # 0 at center line, 1 at edges
    x_left = NOTCH * (1.0 - t)             # concave back edge
    x_right = W * (1.0 - t)                # taper to the right point
    return x_left <= px <= x_right

rows = []
for y in range(H):
    row = []
    for x in range(W):
        hits = 0
        for sy in range(SS):
            for sx in range(SS):
                if inside(x + (sx + .5) / SS, y + (sy + .5) / SS):
                    hits += 1
        row.append(round(15.0 * hits / (SS * SS)))
    rows.append(row)

# pack 4bpp, 2 px per byte, high nibble first
data = []
for row in rows:
    for i in range(0, W, 2):
        hi = row[i]
        lo = row[i + 1] if i + 1 < W else 0
        data.append((hi << 4) | lo)

adv_w = (PAD + W + PAD) * 16
hexrows = []
bpr = (W + 1) // 2
for r in range(H):
    hexrows.append("    " + ", ".join(f"0x{b:02x}" for b in data[r * bpr:(r + 1) * bpr]) + ",")

C = f"""// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AIDlink contributors
//
// GENERATED by tools/gen_arrow_font.py: a single-glyph LVGL font carrying
// a real U+27A4 (black rightwards arrowhead) for the route line — the built-in
// Montserrat fonts don't include it. Padding is baked into adv_w/ofs_x, so the
// span text is just "\\xE2\\x9E\\xA4" with no surrounding spaces.
#include "sdkconfig.h"
#if CONFIG_IDF_TARGET_ESP32S3   // LVGL exists only on the display-capable target
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
{chr(10).join(hexrows)}
}};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
    {{.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}} /* id 0 reserved */,
    {{.bitmap_index = 0, .adv_w = {adv_w}, .box_w = {W}, .box_h = {H}, .ofs_x = {PAD}, .ofs_y = 5}},
}};

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = 0x27A4, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }},
}};

static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
}};

const lv_font_t font_arrow = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {H + 6},
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
}};
#endif  // CONFIG_IDF_TARGET_ESP32S3
"""
out = "/Users/looping/Desktop/AIDlink/firmware-idf/main/font_arrow.c"
open(out, "w").write(C)
# ASCII preview
for row in rows:
    print("".join(" .:-=+*#%@|"[min(v * 10 // 15, 9)] for v in row))
print(f"wrote {out}")
