#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Regenerate the 1-bpp LVGL fonts used by the Board 4 (T3-S3) OLED layout.
#
# WHY 1 bpp: LVGL's built-in Montserrat fonts are 4-bpp anti-aliased. On a
# 1-bit SSD1306 every partial-coverage pixel gets thresholded, so stems break up
# and the text reads as furry noise. Rasterising at --bpp 1 puts the decision at
# design time instead, and the glyphs come out sharp.
#
# WHY THESE SIZES: they are derived from the panel's own 64 px height —
#   band A  8 + bar 3 + band C 16 + band D 8 + band E 8 + band F 12 = 55 px,
# leaving 9 px of inter-band gap. See layout_oled.c.
#
# Charset is deliberately narrow (printable ASCII + U+00B0 degree) to keep the
# tables small; widen the -r ranges if a layout ever needs more.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
main="$here/../firmware-idf/main"
ttf="$here/../firmware-idf/managed_components/lvgl__lvgl/scripts/built_in_font/Montserrat-Medium.ttf"

if [ ! -f "$ttf" ]; then
    echo "error: $ttf not found — run an idf.py build first so LVGL is fetched" >&2
    exit 1
fi

gen() {   # gen <output-name> <pixel-size>
    npx --yes lv_font_conv \
        --font "$ttf" --size "$2" --bpp 1 --format lvgl \
        --lv-include lvgl.h -r 0x20-0x7E -r 0xB0 --no-compress \
        -o "$main/$1.c"
    # Same self-guard the hand-written generators emit (see gen_arrow_font.py):
    # LVGL only exists on the display-capable target, so on the classic ESP32
    # these files must compile to nothing rather than fail on <lvgl.h>.
    python3 - "$main/$1.c" "$2" <<'PY'
import sys
path, size = sys.argv[1], sys.argv[2]
body = open(path).read()
head = ("// SPDX-License-Identifier: Apache-2.0\n"
        "// GENERATED by tools/gen_oled_fonts.sh -- do not edit by hand.\n"
        f"// Montserrat {size}px at 1 bpp for the Board 4 (T3-S3) 128x64 OLED.\n"
        "// Anti-aliased 4bpp fonts smear when thresholded to one bit; this is\n"
        "// rasterised at 1 bpp so the glyph edges are decided at design time.\n"
        '#include "sdkconfig.h"\n'
        "#if CONFIG_IDF_TARGET_ESP32S3   // LVGL exists only on the display-capable target\n")
open(path, "w").write(head + body + "\n#endif\n")
PY
    echo "  $1.c  ($2 px, 1 bpp)"
}

echo "regenerating OLED fonts into $main"
gen font_aid8  8
gen font_aid12 12
gen font_aid16 16
echo "done — rebuild to pick them up"
