#!/usr/bin/env python3
"""Generate main/font_globe.c — a single-glyph LVGL font with a globe/earth
icon mapped at U+1F310 (GLOBE WITH MERIDIANS), drawn programmatically like
font_arrow.c (no font tools needed): outer ring + equator + one meridian
ellipse. 4bpp, 8x supersampled antialiasing."""

import math

W, H = 13, 13          # glyph box
SS = 8                 # supersampling factor
R = 6.0                # outer radius
RING = 1.1             # ring thickness
CX, CY = W / 2.0, H / 2.0

def inside(px, py):
    dx, dy = px - CX, py - CY
    d = math.hypot(dx, dy)
    if d > R:
        return False
    if d >= R - RING:                 # outer ring
        return True
    if abs(dy) <= 0.55:               # equator
        return True
    f = math.hypot(dx / (R * 0.45), dy / R)   # central meridian ellipse
    return 0.86 <= f <= 1.16

rows = []
for y in range(H):
    row = []
    for x in range(W):
        hits = 0
        for sy in range(SS):
            for sx in range(SS):
                if inside(x + (sx + .5) / SS, y + (sy + .5) / SS):
                    hits += 1
        row.append(round(15.0 * hits / (SS * SS)))
    rows.append(row)

# pack 4bpp, 2 px per byte, high nibble first
data = []
for row in rows:
    for i in range(0, W, 2):
        hi = row[i]
        lo = row[i + 1] if i + 1 < W else 0
        data.append((hi << 4) | lo)

adv_w = W * 16
hexrows = []
bpr = (W + 1) // 2
for r in range(H):
    hexrows.append("    " + ", ".join(f"0x{b:02x}" for b in data[r * bpr:(r + 1) * bpr]) + ",")

C = f"""// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AIDlink contributors
//
// GENERATED by tools/gen_globe_font.py: a single-glyph LVGL font carrying a
// globe icon at U+1F310 for the display's internet-connectivity indicator —
// the built-in Montserrat symbol set has no globe. Span/label text is
// "\\xF0\\x9F\\x8C\\x90".
#include "sdkconfig.h"
#if CONFIG_IDF_TARGET_ESP32S3   // LVGL exists only on the display-capable target
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
{chr(10).join(hexrows)}
}};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
    {{.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}} /* id 0 reserved */,
    {{.bitmap_index = 0, .adv_w = {adv_w}, .box_w = {W}, .box_h = {H}, .ofs_x = 0, .ofs_y = 0}},
}};

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = 0x1F310, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }},
}};

static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
}};

const lv_font_t font_globe = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {H},
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
}};
#endif  // CONFIG_IDF_TARGET_ESP32S3
"""
out = "/Users/looping/Desktop/AIDlink/firmware-idf/main/font_globe.c"
open(out, "w").write(C)
# ASCII preview
for row in rows:
    print("".join(" .:-=+*#%@|"[min(v * 10 // 15, 9)] for v in row))
print(f"wrote {out}")
