#!/usr/bin/env python3
"""Generate firmware-idf/main/tzdb_data.c: 1-degree world grid of timezone
indices + per-zone UTC-offset transition tables covering 2026-2028.
Zones are deduped by transition signature (must fit uint8)."""
import sys
from datetime import datetime, timezone, timedelta
from zoneinfo import ZoneInfo
from timezonefinder import TimezoneFinder

OUT = "/Users/looping/Desktop/AIDlink/firmware-idf/main/tzdb_data.c"
T0 = datetime(2026, 1, 1, tzinfo=timezone.utc)
T1 = datetime(2028, 1, 1, tzinfo=timezone.utc)
STEP = timedelta(minutes=30)
MAXTRANS = 8

def signature(name):
    tz = ZoneInfo(name)
    entries = []
    prev = None
    t = T0
    while t < T1:
        off = int(tz.utcoffset(t).total_seconds() // 60)
        if prev is None:
            entries.append((0, off))
            prev = off
        elif off != prev:
            lo, hi = t - STEP, t
            while hi - lo > timedelta(minutes=1):
                mid = lo + (hi - lo) / 2
                mid = mid.replace(second=0, microsecond=0)
                if mid in (lo, hi):
                    break
                if int(tz.utcoffset(mid).total_seconds() // 60) == prev:
                    lo = mid
                else:
                    hi = mid
            entries.append((int(hi.timestamp()), off))
            prev = off
        t += STEP
    if len(entries) > MAXTRANS:
        raise SystemExit(f"{name}: {len(entries)} transitions > {MAXTRANS}")
    return tuple(entries)

def main():
    tf = TimezoneFinder(in_memory=True)
    # pass 1: zone name per cell (centers), row 0 = lat -90..-89, col 0 = lon -180..-179
    cell_names = []
    names = set()
    for r in range(180):
        latc = -90 + r + 0.5
        row = []
        for c in range(360):
            lonc = -180 + c + 0.5
            n = tf.timezone_at(lng=lonc, lat=latc) or "Etc/GMT"
            row.append(n)
            names.add(n)
        cell_names.append(row)
        if r % 30 == 0:
            print(f"grid row {r}/180", file=sys.stderr)

    # pass 2: signatures, dedupe
    sig_of_name = {}
    for n in sorted(names):
        try:
            sig_of_name[n] = signature(n)
        except Exception as e:
            raise SystemExit(f"zone {n}: {e}")
    uniq = sorted(set(sig_of_name.values()))
    if len(uniq) > 255:
        raise SystemExit(f"{len(uniq)} unique signatures > 255")
    idx_of_sig = {s: i for i, s in enumerate(uniq)}
    print(f"{len(names)} zones -> {len(uniq)} unique signatures", file=sys.stderr)

    grid = bytearray(180 * 360)
    for r in range(180):
        for c in range(360):
            grid[r * 360 + c] = idx_of_sig[sig_of_name[cell_names[r][c]]]

    with open(OUT, "w") as f:
        f.write("// SPDX-License-Identifier: Apache-2.0\n")
        f.write("// GENERATED by tools/gen_tzdb.py from IANA tz data via timezonefinder.\n")
        f.write(f"// Coverage {T0.date()} .. {T1.date()}; regenerate with firmware updates.\n")
        f.write('#include "tzdb.h"\n\n')
        f.write(f"const uint8_t TZDB_NZONES = {len(uniq)};\n\n")
        f.write("const tzdb_zone_t TZDB_ZONES[] = {\n")
        for s in uniq:
            ts = ", ".join(f"{{{at}u,{off}}}" for at, off in s)
            f.write(f"    {{ {len(s)}, {{ {ts} }} }},\n")
        f.write("};\n\n")
        f.write("const uint8_t TZDB_GRID[180*360] = {\n")
        for r in range(180):
            row = grid[r * 360:(r + 1) * 360]
            f.write("    " + ",".join(str(b) for b in row) + ",\n")
        f.write("};\n")
    print(f"wrote {OUT}", file=sys.stderr)

if __name__ == "__main__":
    main()
