#!/usr/bin/env python3
"""Generate main/font_tod.c — a single-glyph LVGL font carrying a TOD
(top-of-descent) icon at U+2198: the classic 'hockey stick' — level cruise
segment breaking into a descent slope. Drawn programmatically like
font_arrow/font_globe (4bpp, 8x supersampled)."""
import math
import os

W, H = 16, 12          # glyph box
PAD = 3                # visual padding each side, via ofs_x / adv_w
SS = 8                 # supersampling factor
STROKE = 2.4           # line width

# polyline: cruise (0,1.6)->(7,1.6), then descent to (15.5,11)
SEGS = [((0.0, 1.6), (7.0, 1.6)), ((7.0, 1.6), (15.5, 11.0))]


def seg_dist(p, a, b):
    px, py = p
    ax, ay = a
    bx, by = b
    dx, dy = bx - ax, by - ay
    t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def inside(px, py):
    return any(seg_dist((px, py), a, b) <= STROKE / 2 for a, b in SEGS)


rows = []
for y in range(H):
    row = []
    for x in range(W):
        hits = sum(1 for sy in range(SS) for sx in range(SS)
                   if inside(x + (sx + .5) / SS, y + (sy + .5) / SS))
        row.append(round(15.0 * hits / (SS * SS)))
    rows.append(row)

data = []
for row in rows:
    for i in range(0, W, 2):
        data.append((row[i] << 4) | (row[i + 1] if i + 1 < W else 0))

adv_w = (PAD + W + PAD) * 16
bpr = (W + 1) // 2
hexrows = ["    " + ", ".join(f"0x{b:02x}" for b in data[r * bpr:(r + 1) * bpr]) + ","
           for r in range(H)]

C = f"""// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AIDlink contributors
//
// GENERATED by tools/gen_tod_font.py: single-glyph LVGL font with a TOD
// (top-of-descent) icon at U+2198 — level segment breaking into a descent
// slope. Padding baked into adv_w/ofs_x; span text is just "\\xE2\\x86\\x98".
#include "sdkconfig.h"
#if CONFIG_IDF_TARGET_ESP32S3   // LVGL exists only on the display-capable target
#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
{chr(10).join(hexrows)}
}};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
    {{.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0}} /* id 0 reserved */,
    {{.bitmap_index = 0, .adv_w = {adv_w}, .box_w = {W}, .box_h = {H}, .ofs_x = {PAD}, .ofs_y = 0}},
}};

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = 0x2198, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }},
}};

static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
}};

const lv_font_t font_tod = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {H + 4},
    .base_line = 0,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
}};
#endif  // CONFIG_IDF_TARGET_ESP32S3
"""
out = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "firmware-idf", "main", "font_tod.c")
open(os.path.normpath(out), "w").write(C)
for row in rows:
    print("".join(" .:-=+*#%@|"[min(v * 10 // 15, 9)] for v in row))
print(f"wrote {os.path.normpath(out)}")
